---
name: Testes e verificação de código
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Instalação do Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Troca para o código
      uses: actions/checkout@v2
    - name: Testes e verificação de código
      run: |
        go test ./...
        go vet ./...
        go fmt ./...
    - name: Executa golint
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: './...'
